buildingcodes = {
	
	'AN': 'Annesley Hall (NE; Victoria College Area)',
	'AP': 'Anthropology Building (SW; Huron-Russell-STG-College; Huron-Russell)',
	'AR': 'Architecture Building (SW; Huron-Russell-STG-College; Huron-Russell)',
	'AB': 'Astronomy & Astrophysics Building (SW; STG-Russell)',
	'BA': 'Bahen Centre for Information Technology (SW; STG-Russell)',
	'BF': 'Bancroft Building (SW; Willcocks-Huron-Russell-Spadina; Bancroft)',
	'BI': 'Banting Institute (SE; College-Elizabeth)',
	'CB': 'Best Institute (SE; College-Elizabeth)',
	'BC': 'Birge-Carnegie Library (NE; Victoria College Area)',
	'FE': 'Bloor W 371 (NW; Bloor-Spadina)',
	'NB': 'Borden North (SW; Willcocks-Huron-Russell-Spadina; Bancroft-Spadina)',
	'SB': 'Borden South (SW; Russell-Spadina)',
	'BR': 'Brennan Hall (NE; Southeast of Victoria Campus; Second from Mary St)',
	'BW': 'Burwash Hall (NE; Victoria College Area)',
	'LB': 'Lower Burwash (NE; Victoria College Area)',
	'UB': 'Upper Burwash (NE; Victoria College Area)',
	'TZ': 'C. David Naylor Building (S; From QP-College Second Building Walking North)',
	'CG': 'Canadiana Gallery (QPC; Fifth building west side)',
	'CF': 'Cardinal Flahiff Building (E; QPC-StJoseph-Wellesley-Bay; St. Joseph-St. Basil)',
	'CR': 'Carr Hall (E; QPC-St. Joseph)',
	'ST': 'Central Steam Plant (SW: Huron-Russell-STG-College; Russell Mid)',
	'CN': 'Chestnut Residence (University & Dundas, Walk Dundas Eastward to Chestnut St)',
	'BN': 'Clara Benson Building (W; Harbord-Huron-Classic)',
	'BL': 'Claude T. Bissell Building (NW; Robarts; Sussex-STG)',
	'CX': 'College 245 (--)',
	'CE': 'College 229 (SW; College-Ross)',
	'ZC': 'College 88 (SE; College-Elizabeth)',
	'OG': 'College 92 (SE; College-Elizabeth)',
	'CH': 'Convocation Hall (KCR-KC-Galbraith)',
	'CU': 'Cumberland House (SW; STG-College on the one way street first right)',
	'PT': 'D. L. Pratt Building (S; KC-College; Second from main entrance on KC, left)',
	'DN': 'Dentistry Building (University & Dundas; Spanning Edward-Elm)',
	'PR': 'E. J. Pratt Library (NE; Victoria College Area)',
	'ER': 'Early Learning Centre (NW; Harbord-Spadina-Sussex-Huron; Centre Glen Morris)',
	'ES': 'Earth Sciences Centre (W; Willcocks-Huron-Russell-Spadina; Spanning Bancroft, Huron)',
	'EJ': 'Edward Johnson Building (Philosophers Walk, modern looking)',
	'EH': 'Elmsley Hall (NE; Bay-Charles; St. Mary, Mike Area)',
	'EM': 'Emmanuel College (NE; Vic Area, Queens Park)',
	'EA': 'Engineering Annex (S; STG-College; middle building first street to right)',
	'AD': 'Enrollment Services (--)',
	'EX': 'Exam Centre (S; College-McCaul; Second building south on left past path)',
	'SK': 'Factor-Interwash Faculty of Social Network (N; Bloor-Bedford)',
	'FC': 'Faculty Club (SW; Willcocks-Huron-Russell-Spadina; Path south from Willcocks-Spadina)',
	'FH': 'Falconer Hall (Philosophers Walk, opposing Edward Johnson)',
	'LG': 'Fasken Martineau Building (NW; Spadina-Glen Morris)',
	'FI': 'Fields Institute for Res in Math Sci (SW; Huron-Russell-STG-College; Path from College)',
	'FS': 'Fisher House (NE; Mike Area)',
	'FG': 'Fitzgerald Building (S; Queens Park-College, head west on college and second building to right)',
	'LW': 'Flavelle House (Final building on Philsophers Walk, near QPC)',
	'BH': 'Founders House (NE; Mike Area; Elmsley-St. Joseph)',
	'GA': 'Gage Building (SW; College-Ross; opposite Fields Inst (FI))',
	'GB': 'Galbraith Building (SW; From College-STG go past first road, on right)',
	'GI': 'George Ignatieff Theatre (N; From Hoskin-Devonshire go along Devonshire, on right)',
	'LA': 'Gerald Larkin Building (N; next to George Ignatieff (GI))',
	'SM': 'Gerstein Science Info Centre (KCC; From HH Circle enter KKC, turn left, first building)',
	'GH': 'Gilson House (NE; Mike Area)',
	'GO': 'Goldring Centre (N; from Bloor-Devonshire go along Devonshire second building on right)',
	'GC': 'Goldring Student Centre (NE; Vic Area)',
	'GD': 'Graduate House (NW; From Harbord-Spadina first building)',
	'GU': 'Grad Students Union (SW; From Huron-Bancroft go along Bancroft to fork)',
	'HH': 'Hart House (QPC-N; From QPC-Wellesley go along HH Circle, also facing QPC)',
	'HS': 'Health Sci Building (S; From KC-College go E along College; near College and McCaul)',
	'HU': 'Huron 215 (SW; from Huron-Russell go south on Huron and second building to left)',
	'CA': 'Huron 370 (NW; from Huron-Sussex go south on Huron and on right)',
	'IN': 'Innis College (NW; from STG-Sussex go on Sussex and to right)',
	'IS': 'Innis College Student Residence (NW; from STG-Sussex go north STG and on right)',
	'BT': 'Isabel Bader Theatre (NE; Vic Area)',
	'KL': 'J. M. Kelly Library (NE; from QPC-St. Joseph go along St. Joseph on right)',
	'DR': 'J. Robrt S. Prichard Alumni House (KCC; from KCC go to the triangle road)',
	'JH': 'Jackman Humanities Building (NW; STG-Bloor)',
	'RL': 'Robarts Library (NW; STG-Harbord-Huron-Sussex)',
	'KX': 'Knox College (KCC; opposite Gerstein, near Convocation, perpendicular UC)',
	'KP': 'Koffler House (SW; Spadina-Bancroft)',
	'KS': 'Koffler Student Services Centre (SW; from STG-College go along STG on left)',
	'LM': 'Lash Miller Chem Labs (SW; STG-Willcocks Pathway)',
	'MB': 'Lassonde Mining Building (S; from College-KC go along KC on right, or College east on left)',
	'WR': 'Leighton Goldie McCarthy House (---)',
	'PB': 'Leslie L. Dan Pharmacy Building (S; from QP-College go on the diagonal path and first turn left)',
	'LI': 'Lillian Massey Building (NE; from QP-Bloor go on QP on left)',
	'LC': 'Loretto College (NE; St. Mary behind Rowell Jackman)',
	'SO': 'Louis B. Stewart Observatory (KCC; from HH Circle go to UC and look opposite)',
	'GM': 'Luella Massey Studio Theatre (NW; from Harbord-Sussex go Sussex west then first left down street)',
	'MM': 'MacDonald-Mowat House (KCC; on STG go near Knox College)',
	'MG': 'Margaret Addison Hall (NE; Vic Area)',
	'MN': 'Maritain House (NE; Mike Area)',
	'MA': 'Massey College (NW; on Hoskin-Devonshire)',
	'GE': 'Max Gluskin House (NE; from STG-Bloor go STG south on right near looped road)',
	'RM': 'McCaul 254/256 (S; on KCC-College go east College to McCaul, south McCaul on right)',
	'MZ': 'McCorkell House (NE; Mike Area)',
	'MP': 'McLennan Physical Labs (SW; from STG-Russell go Russell west on left)',
	'MR': 'McMurrich Building (S; from QPC-College go along pathways, in Discovery Area)',
	'MC': 'Mech Eng Building (S; from KC go on Discovery Ln)',
	'MS': 'Med Sci Building (KCC; KCC-KC opposing UC building)',
	'MH': 'More House (NE; Mike Area)',
	'MO': 'Morrison Hall (NW; from STG-Harbord go STG south on left)',
	'MU': 'Munk School at Trinity, Graham Library (Trinity Area)',
	'MK': 'Munk School at Observatory (N; Bloor-Devonshire)',
	'AH': 'Muzzo Family at Alumni Hall (NE; QPC-St. Joseph go along St. Joseph on right)',
	'NR': 'New College III (SW; Spadina-Willcocks)',
	'VI': 'Nona Macdonald Visitors Centre (KCC; next to Knox College (KX))',
	'NF': 'Northrop Frye Hall (NE; Vic Area)',
	'OH': 'Odette (Louis) Hall (NE; Mike Area)',
	'OA': 'Old Admin Building (---)',
	'OI': 'Ontario Institute for Studies in Education (N; Exactly on Bloor-Devonshire)',
	'PH': 'Phalen House (NE; Mike Area)',
	'PG': 'Physical Geography Building (SW; from STG-College go STG north, by STG-Galbraith)',
	'PI': 'Pontifical Institute of Mediaeval Studies (NE; Vic Area)',
	'ME': 'Queens Park E 39 (---)',
	'XQ': 'Queens Park E 43 (---)',
	'ML': 'Queens Park E 39A (---)',
	'PL': 'Queens Park 90 (---)',
	'RW': 'Ramsay Wright Labs (NE; STG-Harbord opposing Robarts)',
	'RG': 'Regis College (E; QPC-Wellesley)',
	'RU': 'Rehabilitation Sciences Building (University & Dundas near Elm)',
	'RS': 'Rosebrugh Building (S; Discovery Ln near Med Sci (MS))',
	'RT': 'Rotman Building (NW; from STG-Harbord/Hoskin go STG north on right)',
	'RJ': 'Rowell Jackman Hall (NE; Vic Area)',
	'SF': 'Sanford Fleming Building (S; From KC-College go KC north and past leftward street)',
	'CS': 'School of Continuing Studies (NW; From STG-Bloor go STG south on right)',
	'GS': 'School of Grad Studies (W; STG-Willcocks)',
	'SS': 'Sidney Smith Hall (W; from STG-Willcocks go Willcocks on right)',
	'SI': 'Simcoe Hall (SW; from STG-Russell go STG south to Galbraith, go Galbraith on left)',
	'SD': 'Sir Daniel Wilson Res (KCC; UC Area)',
	'TR': 'Soldiers Tower (KCC; HH Area)',
	'TT': 'Spadina 455 (---)',
	'SA': 'Spadina 713 (---)',
	'XG': 'Spadina 665 (---)',
	'IA': 'Spadina 703 (---)',
	'FA': 'Spadina 720 (---)',
	'SP': 'Spadina 1 (Spadina Circle)',
	'CD': 'Spadina 56 (---)',
	'BS': 'St Basils Church (NE; Mike Area)',
	'IR': 'STG 121 (---)',
	'SG': 'STG 49 (---)',
	'WA': 'STG 123 (---)',
	'HI': 'St Hildas College (NW; from Hoskin-Devonshire go Devonshire north on left)',
	'SN': 'Stephenson House (NE; Vic Area)',
	'EP': 'Stewart Building (S; College-Murray)',
	'SV': 'Sullivan House (NE; Mike Area)',
	'SU': 'Sussex 40 (NW; from STG-Sussex go Sussex on right)',
	'SC': 'Sussex Court (NW; from STG-Sussex go Sussex on left)',
	'TF': 'Teefy Hall (NE; Mike Area)',
	'DC': 'Terrence Donnelly Center for Cellular + Biomolecular Research (Discovery Area)',
	'RB': 'Thomas Fisher Rare Books Library (Robarts)',
	'TH': 'Toronto School of Theology (NE; Mike Area)',
	'TC': 'Trinity College (Philosophers Walk/Hoskin)',
	'UC': 'University College (KCC)',
	'UP': 'UC Union (UC Area on STG)',
	'VA': 'Varsity Centre (N)',
	'VP': 'Varsity Pavillion (N)',
	'VC': 'Victoria College (NE)',
	'WB': 'Wallberg Building (SW; spanning STG to KC on College)',
	'JP': 'Wellesley W 90 (NE; Mike Area)',
	'WE': 'Wetmore Hall (W; NC Area on Classic-Huron)',
	'WT': 'Whitney Hall (NW; STG-Hoskin diagonally opposite to Robarts)',
	'WI': 'Wilson Hall (W; NC Area on Spadina-Willcocks)',
	'WN': 'Windle House (NE; Mike Area)',
	'WW': 'Woodsworth College (NW; from STG-Bloor go STG south and on left)',
	'WO': 'Woodsworth Residence (NW; STG-Bloor)',
	'WY': 'Wycliffe College (Directly opposing Trinity College (TC))',

}